from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import arabic_reshaper
from bidi.algorithm import get_display


# =========================
# تسجيل الخط
# =========================
pdfmetrics.registerFont(TTFont('Arabic', 'Amiri-Regular.ttf'))


def fix_arabic(text):
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


def create_pdf(pages, output_path="translated.pdf"):

    doc = SimpleDocTemplate(
        output_path,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=50
    )

    # =========================
    # Styles (🔥 محسنة)
    # =========================
    title_style = ParagraphStyle(
        name="Title",
        fontName="Arabic",
        fontSize=26,   # 🔥 كبير
        alignment=TA_CENTER,
        spaceAfter=30
    )

    page_title_style = ParagraphStyle(
        name="PageTitle",
        fontName="Arabic",
        fontSize=18,   # 🔥 أكبر
        alignment=TA_RIGHT,
        spaceAfter=15
    )

    en_style = ParagraphStyle(
        name="EN",
        fontName="Arabic",
        fontSize=13,
        alignment=TA_RIGHT,
        spaceAfter=4
    )

    ar_style = ParagraphStyle(
        name="AR",
        fontName="Arabic",
        fontSize=15,   # 🔥 العربي أكبر
        alignment=TA_RIGHT,
        spaceAfter=12
    )

    signature_style = ParagraphStyle(
        name="Signature",
        fontName="Arabic",
        fontSize=14,
        alignment=TA_CENTER,
        spaceBefore=40
    )

    content = []

    # =========================
    # الغلاف
    # =========================
    content.append(Spacer(1, 120))
    content.append(Paragraph(fix_arabic("📘 ملف الترجمة"), title_style))
    content.append(Spacer(1, 30))
    content.append(Paragraph("Generated by Abdullah Almakhzomi", signature_style))
    content.append(PageBreak())

    # =========================
    # الصفحات
    # =========================
    for page in pages:

        lines = page.split("\n")

        i = 0

        while i < len(lines):

            line = lines[i].strip()

            if not line:
                i += 1
                continue

            # 📄 عنوان الصفحة
            if "📄 الصفحة" in line:
                content.append(Paragraph(fix_arabic(line), page_title_style))
                content.append(Spacer(1, 10))
                i += 1
                continue

            # 🔥 EN + AR تحت بعض
            if i + 1 < len(lines):

                en_line = lines[i].strip()
                ar_line = lines[i + 1].strip()

                # إنجليزي
                content.append(Paragraph(en_line, en_style))

                # عربي
                content.append(Paragraph(fix_arabic(ar_line), ar_style))

                content.append(Spacer(1, 8))

                i += 2
            else:
                content.append(Paragraph(fix_arabic(line), ar_style))
                i += 1

        content.append(PageBreak())

    # =========================
    # التوقيع
    # =========================
    content.append(Paragraph(fix_arabic("✨ تم الإنشاء بواسطة عبدالله المخزومي"), signature_style))

    doc.build(content)

    return output_path
