from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.colors import HexColor
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import arabic_reshaper
from bidi.algorithm import get_display


# =========================
# الخط
# =========================
pdfmetrics.registerFont(TTFont('Arabic', 'Amiri-Regular.ttf'))


def fix_arabic(text):
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


# =========================
# ترقيم الصفحات
# =========================
def add_page_number(canvas, doc):
    page_num = canvas.getPageNumber()
    canvas.setFont("Arabic", 10)
    canvas.drawCentredString(300, 20, f"{page_num}")


# =========================
# خلفية الغلاف
# =========================
def draw_cover(canvas, doc):
    canvas.setFillColor(HexColor("#0f172a"))
    canvas.rect(0, 0, 595, 842, fill=1)


# =========================
# إنشاء PDF
# =========================
def create_pdf(pages, subject_name="Translation File", output_path="translated.pdf"):

    doc = SimpleDocTemplate(output_path)

    # =========================
    # Styles
    # =========================
    title_style = ParagraphStyle(
        name="Title",
        fontName="Arabic",
        fontSize=28,
        alignment=TA_CENTER,
        textColor=HexColor("#ffffff"),
        spaceAfter=30
    )

    subject_style = ParagraphStyle(
        name="Subject",
        fontName="Arabic",
        fontSize=18,
        alignment=TA_CENTER,
        textColor=HexColor("#38bdf8"),
        spaceAfter=20
    )

    subtitle_style = ParagraphStyle(
        name="Subtitle",
        fontName="Arabic",
        fontSize=14,
        alignment=TA_CENTER,
        textColor=HexColor("#94a3b8"),
        spaceAfter=20
    )

    page_title_style = ParagraphStyle(
        name="PageTitle",
        fontName="Arabic",
        fontSize=18,
        alignment=TA_RIGHT,
        textColor=HexColor("#0f172a"),
        spaceAfter=15
    )

    en_style = ParagraphStyle(
        name="EN",
        fontName="Arabic",
        fontSize=13,
        alignment=TA_RIGHT,
        textColor=HexColor("#334155"),
        spaceAfter=4
    )

    ar_style = ParagraphStyle(
        name="AR",
        fontName="Arabic",
        fontSize=16,
        alignment=TA_RIGHT,
        textColor=HexColor("#000000"),
        spaceAfter=10
    )

    content = []

    # =========================
    # الغلاف
    # =========================
    content.append(Spacer(1, 200))
    content.append(Paragraph(fix_arabic("📘 ملف الترجمة"), title_style))
    content.append(Paragraph(fix_arabic(subject_name), subject_style))
    content.append(Paragraph("Generated by Abdullah Almakhzomi", subtitle_style))
    content.append(PageBreak())

    # =========================
    # الصفحات
    # =========================
    for page in pages:

        lines = page.split("\n")
        i = 0

        while i < len(lines):

            line = lines[i].strip()

            if not line:
                i += 1
                continue

            if "📄 الصفحة" in line:
                content.append(Paragraph(fix_arabic(line), page_title_style))
                i += 1
                continue

            if i + 1 < len(lines):
                en_line = lines[i]
                ar_line = lines[i + 1]

                content.append(Paragraph(en_line, en_style))
                content.append(Paragraph(fix_arabic(ar_line), ar_style))

                i += 2
            else:
                content.append(Paragraph(fix_arabic(line), ar_style))
                i += 1

        content.append(Spacer(1, 15))
        content.append(PageBreak())

    # =========================
    # النهاية
    # =========================
    content.append(Spacer(1, 200))
    content.append(Paragraph(fix_arabic("✨ انتهى الملف"), title_style))
    content.append(Paragraph(fix_arabic("تمت الترجمة بواسطة عبدالله المخزومي"), subject_style))

    # =========================
    # بناء
    # =========================
    doc.build(
        content,
        onFirstPage=draw_cover,
        onLaterPages=add_page_number
    )

    return output_path
