from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import arabic_reshaper
from bidi.algorithm import get_display


# =========================
# تسجيل الخط
# =========================
pdfmetrics.registerFont(TTFont('Arabic', 'Amiri-Regular.ttf'))


# =========================
# تصحيح العربي
# =========================
def fix_arabic(text):
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


def create_pdf(pages, output_path="translated.pdf"):

    doc = SimpleDocTemplate(output_path)

    # =========================
    # Styles
    # =========================
    title_style = ParagraphStyle(
        name="Title",
        fontName="Arabic",
        fontSize=20,
        alignment=TA_CENTER,
        spaceAfter=20
    )

    page_title_style = ParagraphStyle(
        name="PageTitle",
        fontName="Arabic",
        fontSize=14,
        alignment=TA_RIGHT,
        spaceAfter=10
    )

    text_style = ParagraphStyle(
        name="Text",
        fontName="Arabic",
        fontSize=12,
        alignment=TA_RIGHT,
        leading=18
    )

    signature_style = ParagraphStyle(
        name="Signature",
        fontName="Arabic",
        fontSize=12,
        alignment=TA_CENTER,
        spaceBefore=30
    )

    content = []

    # =========================
    # الغلاف
    # =========================
    content.append(Spacer(1, 100))
    content.append(Paragraph(fix_arabic("📘 ملف الترجمة"), title_style))
    content.append(Spacer(1, 20))
    content.append(Paragraph("Generated by Abdullah Almakhzomi", signature_style))
    content.append(PageBreak())

    # =========================
    # الصفحات
    # =========================
    for page in pages:

        lines = page.split("\n")

        for line in lines:

            line = line.strip()

            if not line:
                continue

            # عنوان الصفحة
            if "📄 الصفحة" in line:
                content.append(Paragraph(fix_arabic(line), page_title_style))
            else:
                content.append(Paragraph(fix_arabic(line), text_style))

        content.append(PageBreak())

    # =========================
    # التوقيع
    # =========================
    content.append(Paragraph(fix_arabic("✨ تم الإنشاء بواسطة عبدالله المخزومي"), signature_style))

    doc.build(content)

    return output_path